### ISSUE TITLE
QIIME pipeline failure running 'pick_closed_reference_otus.py'

### ISSUE THREAD

**Issue by pjbriggs** [pjbriggs/Amplicon_analysis-galaxy#10]
Running the `QIIME` pipeline fails when attempting to run `pick_closed_reference_otus.py` (from the QIIME package):

    Traceback (most recent call last):
      File "/home/pjb/scratchpad/test_Amplicon_analysis-galaxy/galaxy_v16.10/local_tool_dependencies/qiime/1.8.0/bin/pick_closed_reference_otus.py", line 144, in <module>
        main()
      File "/home/pjb/scratchpad/test_Amplicon_analysis-galaxy/galaxy_v16.10/local_tool_dependencies/qiime/1.8.0/bin/pick_closed_reference_otus.py", line 140, in main
        status_update_callback=status_update_callback)
      File "/home/pjb/scratchpad/test_Amplicon_analysis-galaxy/galaxy_v16.10/local_tool_dependencies/qiime/1.8.0/lib/python2.7/site-packages/qiime/workflow/upstream.py", line 442, in run_pick_closed_reference_otus
        close_logger_on_success=close_logger_on_success)
      File "/home/pjb/scratchpad/test_Amplicon_analysis-galaxy/galaxy_v16.10/local_tool_dependencies/qiime/1.8.0/lib/python2.7/site-packages/qiime/workflow/util.py", line 116, in call_commands_serially
        raise WorkflowError, msg
    qiime.workflow.util.WorkflowError: 
    
    *** ERROR RAISED DURING STEP: Pick OTUs
    Command run was:
     python /opt/gridware/apps/gcc/qiime/1.8.0/bin/parallel_pick_otus_uclust_ref.py -i Multiplexed_files/multiplexed_linearized.fasta -o closed_ref//uclust_ref_picked_otus -r /home/pjb/scratchpad/test_Amplicon_Analysis_Pipeline/ReferenceData/gg_13_8_otus/rep_set/97_otus.fasta -T --jobs_to_start 32 --max_rejects 8 --stepwords 8 --enable_rev_strand_match --word_length 8 --max_accepts 1
    Command returned exit status: 2
    Stdout:
    
    Stderr
    python: can't open file '/opt/gridware/apps/gcc/qiime/1.8.0/bin/parallel_pick_otus_uclust_ref.py': [Errno 2] No such file or directory

The failure is due to QIIME looking for a file in the non-existent directory `/opt/gridware/apps/gcc/qiime/1.8.0/bin/`, which appears in the `Config_QIIME/.qiime_config` file included in the original repository. 

Obviously this path is likely to be incorrect for general installations of QIIME, furthermore I think this file is redundant and should be removed from the repository.

**UPDATE** this file *is* needed for now - see https://github.com/MTutino/Amplicon_analysis/issues/6 for PR proposing alternative fix.

**Comment by pjbriggs** [comment]
PR was merged so close this issue for now.
