### ISSUE TITLE
Improve error reporting for problems with mapping file

### ISSUE THREAD

**Issue by pjbriggs** [pjbriggs/Amplicon_analysis-galaxy#27]
When there are problems with the mapping file (`Metatable.txt`) it would be useful to improve the reporting of the specific issues by capturing the outputs from the `Metatable_log` output directory - there should be both a `Metatable.log` and `Metatable.html` file.

**Comment by pjbriggs** [comment]
In the `Amplicon_analysis_pipeline.sh` script, the QIIME `validate_mapping_file.py` is run to check the metatable file. If the script detects a problem then it should write the following message to stdout and exit with status 1:

    Some errors have been found in the Metatable.txt file. Correct them before to run again the script
   You can find information about the errors in Metatable_log/Metatable.log file.

However it appears that a "bad" metatable file can cause the validator to exit prematurely with an exception, for example: using a "categories" file instead of a "metatable" file gives:

    Fatal error: Exit code 1 ()
    Traceback (most recent call last):
      File "/mnt/rvmi/centaurus/galaxy/production/local_tools/Amplicon_analysis/tool_dependencies/qiime/1.8.0/bin/validate_mapping_file.py", line 161, in <module>
        main()
      File "/mnt/rvmi/centaurus/galaxy/production/local_tools/Amplicon_analysis/tool_dependencies/qiime/1.8.0/bin/validate_mapping_file.py", line 157, in main
        disable_primer_check, added_demultiplex_field, suppress_html)
      File "/mnt/rvmi/centaurus/galaxy/production/local_tools/Amplicon_analysis/tool_dependencies/qiime/1.8.0/lib/python2.7/site-packages/qiime/check_id_map.py", line 95, in check_mapping_file
        added_demultiplex_field, strip_quotes=False, suppress_stripping=True)
      File "/mnt/rvmi/centaurus/galaxy/production/local_tools/Amplicon_analysis/tool_dependencies/qiime/1.8.0/lib/python2.7/site-packages/qiime/check_id_map.py", line 168, in process_id_map
        suppress_stripping)
      File "/mnt/rvmi/centaurus/galaxy/production/local_tools/Amplicon_analysis/tool_dependencies/qiime/1.8.0/lib/python2.7/site-packages/qiime/parse.py", line 135, in parse_mapping_file
        raise QiimeParseError, "No header line was found in mapping file."
    qiime.parse.QiimeParseError: No header line was found in mapping file.

**Comment by pjbriggs** [comment]
Some progress made on this with PR #33, so closing for now.
